'use client';
import PenaltiesPanel,{PenaltySummary} from './penalties-panel';
import { halfForRound,teamBalance } from '@/lib/penalties';
import { useCallback,useEffect,useRef,useState } from 'react';
import { Activity,BarChart3,Coins,ArrowDownToLine,ArrowUpRight,CalendarDays,Check,CheckCircle2,ChevronRight,Clock3,Database,FileUp,History,Info,LockKeyhole,RefreshCw,Shield,TriangleAlert,Trophy,Users,X } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from '@/components/ui/sheet';
import { Skeleton } from '@/components/ui/skeleton';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { TEAM_NAMES,TEAM_COLORS,initials,displayDate,latestByRound,type Archive,type Snapshot } from '@/lib/model';

function Crest({name}:{name:string}){return <span className="crest" style={{backgroundColor:TEAM_COLORS[TEAM_NAMES.indexOf(name)]}} aria-hidden="true">{initials(name)}</span>}
function Status({present}:{present:boolean|undefined}){return <span className={'badge '+(present===undefined?'unknown':present?'present':'absent')}>{present===undefined?<Info/>:present?<CheckCircle2/>:<Clock3/>}{present===undefined?'Nessuna lettura':present?'Inserita':'Non inserita'}</span>}
function Blank({title,description}:{title:string;description:string}){return <Empty className="blank-panel"><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader></Empty>}
const fixtures=[['AC Idovalproico','Atletico Fontanelle'],['FDS Sballo','FC LBVLA'],['Salamandre','FC SEMINI'],['Pro Spritz','Real Hasbulla'],['FC Villaggio Mau Mau','I PIPPISTRELLI']];

export default function Dashboard(){
  const [view,setView]=useState('monitor');
  const [data,setData]=useState<Archive|null>(null),[round,setRound]=useState('1'),[filter,setFilter]=useState('all');
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[detail,setDetail]=useState<string|null>(null);
  const [importOpen,setImportOpen]=useState(false),[file,setFile]=useState<File|null>(null),[importing,setImporting]=useState(false),[syncing,setSyncing]=useState(false),[importError,setImportError]=useState(''),[message,setMessage]=useState('');
  const [now,setNow]=useState(0);const mounted=useRef(true);const requestId=useRef(0);
  const refresh=useCallback(async()=>{const request=++requestId.current;setLoading(true);setError('');try{const res=await fetch('/api/archive',{cache:'no-store'});const result=await res.json() as Archive & {error?:string};if(!res.ok)throw new Error(result.error);if(mounted.current&&request===requestId.current)setData(result);}catch(e){if(mounted.current&&request===requestId.current)setError(e instanceof Error?e.message:'Lettura non riuscita.');}finally{if(mounted.current&&request===requestId.current)setLoading(false);}},[]);
  useEffect(()=>{mounted.current=true;refresh();setNow(Date.now());const tick=setInterval(()=>{setNow(Date.now());if(document.visibilityState==='visible')refresh();},60000);const onVisible=()=>{if(document.visibilityState==='visible')refresh();};document.addEventListener('visibilitychange',onVisible);return()=>{mounted.current=false;clearInterval(tick);document.removeEventListener('visibilitychange',onVisible)}},[refresh]);
  const byRound=latestByRound(data?.snapshots??[]),current=byRound.get(Number(round));
  const rows=current?.teams??[],missing=rows.filter(t=>!t.present);
  const stale=current&&now-Date.parse(current.observed_at)>15*60*1000;
  const visible=rows.filter(t=>filter==='all'||(filter==='present'?t.present:!t.present));
  const readings=(data?.snapshots??[]).filter(s=>s.round===Number(round));
  const detailRows=readings.filter(s=>s.teams.some(t=>t.name===detail));
  const detailEvents=(data?.events??[]).filter(e=>e.team_key===detail&&e.round===Number(round));
  async function upload(){
    if(!file)return;setImporting(true);setImportError('');setMessage('');
    try{if(file.size>262144)throw new Error('Il file supera 256 KB.');const body=await file.text();JSON.parse(body);
      const response=await fetch('/api/archive',{method:'POST',headers:{'Content-Type':'application/json'},body});const result=await response.json() as {error?:string;imported:number;duplicates:number};if(!response.ok)throw new Error(result.error);
      setMessage(`${result.imported} nuove letture archiviate · ${result.duplicates} già presenti.`);setFile(null);await refresh();
    }catch(e){setImportError(e instanceof SyntaxError?'Il file non contiene JSON valido.':e instanceof Error?e.message:'Importazione non riuscita.');}finally{setImporting(false)}
  }
  async function syncNow(){
    setSyncing(true);setError('');setMessage('');
    try{const response=await fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({round:Number(round)})});const result=await response.json() as {error?:string;imported?:number;duplicates?:number};if(!response.ok)throw new Error(result.error);setMessage(`Giornata ${round} sincronizzata · ${result.imported??0} nuova lettura · ${result.duplicates??0} già presente.`);await refresh();}
    catch(e){setError(e instanceof Error?e.message:'Sincronizzazione non riuscita.');}finally{setSyncing(false)}
  }
  function exportData(){if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data.snapshots,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='fantamonitor-letture.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  const openImport=()=>{setImportOpen(true);setMessage('');setImportError('')};
  return <div className="app-shell">
    <header className="topbar"><a href="/" className="brand" aria-label="FANTAMONITOR home"><span className="brand-mark">FM</span>FANTAMONITOR</a><div className="account-tools"><span className="lock-label"><LockKeyhole size={14}/>Area privata</span><form action="/api/auth/logout" method="post"><button className="signout-btn" type="submit">Esci</button></form></div></header>
    <div className="league-banner"><div className="league-label"><span className="league-emblem"><Shield size={26}/></span><div><strong>CheFantaVitaE10</strong><span className="season">Stagione 2026 / 27 · Serie A</span></div></div><span className="league-mode">CLASSIC</span></div>
    <Tabs value={view} onValueChange={value=>value==='stats'?window.location.assign('/stats'):setView(value)}>
      <div className="navigation"><TabsList variant="line" className="main-tabs" style={{gridTemplateColumns:'repeat(5,minmax(0,1fr))'}} aria-label="Viste della lega"><TabsTrigger value="monitor"><Activity/>Formazioni</TabsTrigger><TabsTrigger value="penalties"><Coins/>Gettoni e penalità</TabsTrigger><TabsTrigger value="history"><History/>Storico</TabsTrigger><TabsTrigger value="competition"><Trophy/>Competizione</TabsTrigger><TabsTrigger value="stats"><BarChart3/>Statistiche</TabsTrigger></TabsList><div className="tools"><button className="btn" onClick={syncNow} disabled={!data?.canManage||syncing} title="Acquisisce la giornata dal connettore autenticato"><RefreshCw className={syncing?'spin':''}/>{syncing?'Sincronizzazione…':'Sincronizza ora'}</button><button className="btn" onClick={refresh} disabled={loading}><RefreshCw className={loading?'spin':''}/>Rileggi dati</button><button disabled={!data?.canManage} className="btn primary" onClick={openImport}><FileUp/>Importa lettura</button></div></div>
      {error&&<div role="alert" className="error-banner"><TriangleAlert size={20}/><span>{error}{data?' Le informazioni visibili sono quelle dell’ultima lettura riuscita.':''}</span>{error==='Accesso richiesto.'&&<a href="/login" target="_top">Accedi</a>}</div>}
      <TabsContent value="monitor">
        <div className="page-heading"><div><div className="eyebrow">Serie A · CheFantaVitaE10</div><h1>Monitor formazioni</h1><div className="sync-note"><Clock3/>{current?`Ultima osservazione: ${displayDate(current.observed_at)}`:'Seleziona una giornata o importa una lettura.'}</div></div><Select value={round} onValueChange={setRound}><SelectTrigger className="round-select" aria-label="Giornata da monitorare"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:35},(_,i)=><SelectItem key={i} value={String(i+1)}>Giornata {String(i+1).padStart(2,'0')}</SelectItem>)}</SelectContent></Select></div>
        <PenaltySummary data={data} round={Number(round)} onOpen={()=>setView('penalties')}/>{!data&&loading?<div aria-label="Caricamento archivio" className="space-y-6"><Skeleton className="h-72 w-full"/><Skeleton className="h-96 w-full"/></div>:current?<>
          <section className="scoreboard" aria-label="Riepilogo formazioni osservate"><div className="score-main"><div className="score-label"><span className="eyebrow">Giornata {String(round).padStart(2,'0')} / 35</span><span className="scope-chip">{error?'Archivio non raggiungibile':stale?'Dati da aggiornare':'Ultima lettura disponibile'}</span></div><div className="score-number"><strong>{current.inserted}</strong><span>/ {current.expected_total}</span></div><p className="score-caption">formazioni presenti nell’ultima osservazione</p><div className="team-bars" aria-label="Stato delle dieci squadre">{rows.map(t=><button key={t.name} className={'team-bar '+(t.present?'present':'')} onClick={()=>setDetail(t.name)} aria-label={`${t.name}: ${t.present?'inserita':'non inserita'}`} title={t.name}/>)}</div><div className="legend"><span><i className="swatch"/>Inserita</span><span><i className="swatch waiting"/>Non inserita</span></div></div><div className="score-aside"><div className="aside-row"><CalendarDays/><div><strong>Scadenza da verificare</strong><p>Il termine esatto della giornata non è ancora disponibile nell’archivio.</p></div></div><div className="aside-row"><Database/><div><strong>Aggiornamento su importazione</strong><p>La sincronizzazione automatica con Fantacalcio non è ancora attiva.</p></div></div><div className="aside-row"><Shield/><div><strong>Gettoni e penalità per girone</strong><p>Prima assenza gratuita, poi 5 € per ogni mancata consegna verificata.</p></div></div></div></section>
          <div className="monitor-grid"><section className="panel"><div className="panel-head"><h2>Le squadre <span className="muted">· 10</span></h2><Tabs value={filter} onValueChange={setFilter}><TabsList className="status-tabs" aria-label="Filtra per presenza"><TabsTrigger value="all">Tutte</TabsTrigger><TabsTrigger value="absent">Non inserite</TabsTrigger><TabsTrigger value="present">Inserite</TabsTrigger></TabsList></Tabs></div><Table className="team-table"><TableHeader><TableRow><TableHead>Squadra</TableHead> <TableHead>Stato osservato</TableHead><TableHead className="detail-col"><span className="sr-only">Dettagli</span></TableHead></TableRow></TableHeader><TableBody>{visible.map(t=><TableRow key={t.name}><TableCell><button className="team-name" onClick={()=>setDetail(t.name)}><Crest name={t.name}/><span><strong>{t.name}</strong><small className="team-accounting">{teamBalance(t.name,halfForRound(Number(round)),data?.reviews??[]).remaining} gettone residuo · {teamBalance(t.name,halfForRound(Number(round)),data?.reviews??[]).penalty} € nel girone</small></span></button></TableCell><TableCell><Status present={t.present}/></TableCell><TableCell className="detail-col"><button className="detail-button" onClick={()=>setDetail(t.name)} aria-label={`Dettagli ${t.name}`}>Dettaglio<ChevronRight size={14}/></button></TableCell></TableRow>)}</TableBody></Table>{!visible.length&&<Blank title="Nessuna squadra in questo filtro" description="Tutte le squadre hanno uno stato diverso da quello selezionato."/>}</section><aside className="side-stack"><section className="panel"><TriangleAlert className="warning-icon"/><h2>{missing.length} da ricontrollare</h2><p>Risultavano senza formazione all’ultima lettura.</p><ul className="waiting-list">{missing.map(t=><li key={t.name}><button onClick={()=>setDetail(t.name)}>{t.name}</button></li>)}</ul>{!missing.length&&<p>Tutte le squadre risultano presenti.</p>}</section><section className="panel method"><h2>Leggere il dato</h2><p>“Non inserita” descrive il momento del controllo. Un recupero automatico o un intervento dell’admin richiede una verifica separata del log.</p><a className="detail-button" href={current.source_url} target="_blank" rel="noreferrer">Apri la fonte<ArrowUpRight/></a></section></aside></div><p className="footnote">Orari delle osservazioni in Italia · Il momento del controllo non coincide con quello dell’invio.</p>
        </>:<section className="panel"><Blank title={`Nessuna lettura per la giornata ${round}`} description="Questa giornata non è ancora stata acquisita. Importa un’osservazione per visualizzare lo stato delle dieci squadre."/></section>}
      </TabsContent>
      <TabsContent value="penalties"><PenaltiesPanel data={data} round={Number(round)} onSaved={refresh}/></TabsContent>
      <TabsContent value="history">
        <div className="page-heading"><div><div className="eyebrow">Il registro della stagione</div><h1>Storico formazioni</h1><div className="sync-note">{data?.snapshots.length??0} letture archiviate · {byRound.size} giornate osservate su 35</div></div><button className="btn" onClick={exportData} disabled={!data}><ArrowDownToLine/>Esporta JSON</button></div>
        <section className="panel mobile-history"><div className="panel-head"><h2>Stato per giornata</h2><Select value={round} onValueChange={setRound}><SelectTrigger aria-label="Giornata dello storico"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:35},(_,i)=><SelectItem key={i} value={String(i+1)}>Giornata {i+1}</SelectItem>)}</SelectContent></Select></div><p className="footnote px-4">{current?displayDate(current.observed_at):'Nessuna lettura disponibile'}</p>{TEAM_NAMES.map(name=><button key={name} className="mobile-history-row" onClick={()=>setDetail(name)}><strong>{name}</strong><Status present={current?.teams.find(t=>t.name===name)?.present}/></button>)}</section><section className="panel history-matrix"><div className="panel-head"><h2>Squadre × giornate</h2><small>Ultimo stato osservato per giornata</small></div><Table className="matrix"><TableHeader><TableRow><TableHead>Squadra</TableHead>{Array.from({length:35},(_,i)=><TableHead key={i}>{i+1}</TableHead>)}</TableRow></TableHeader><TableBody>{TEAM_NAMES.map(name=><TableRow key={name}><TableCell>{name}</TableCell>{Array.from({length:35},(_,i)=>{const s=byRound.get(i+1),t=s?.teams.find(t=>t.name===name);return <TableCell key={i}><button className={'heat-cell '+(t?(t.present?'present':'absent'):'')} aria-label={`${name}, giornata ${i+1}: ${t?(t.present?'inserita':'non inserita'):'nessuna lettura'}`} title={s?displayDate(s.observed_at):'Nessuna lettura'} onClick={()=>{setRound(String(i+1));setDetail(name)}}>{t?(t.present?'✓':'−'):'·'}</button></TableCell>})}</TableRow>)}</TableBody></Table></section><div className="legend"><span><i className="swatch"/>Inserita</span><span><i className="swatch waiting"/>Non inserita</span><span><i className="swatch unknown"/>Nessuna lettura</span></div><div className="history-grid"><section className="panel"><div className="panel-head"><h2>Registro delle letture</h2><small>Più recenti prima</small></div><div className="timeline">{[...(data?.snapshots??[])].reverse().slice(0,30).map((s,i)=><div className="timeline-row" key={s.observed_at+s.round}><div><strong>Giornata {s.round}</strong><p>{displayDate(s.observed_at)} · {new Date(s.observed_at).toLocaleTimeString('it-IT',{timeZone:'Europe/Rome'})}</p></div><span className="timeline-count">{s.inserted}<small className="muted">/10</small></span></div>)}</div></section><section className="panel"><div className="panel-head"><h2>Evidenze di invio</h2><small>Log verificati</small></div><div className="timeline">{(data?.events??[]).map((e,i)=><div className="timeline-row" key={i}><div><strong>{e.team_key}</strong><p>{e.source_label}</p><p>{e.source_time_text} · orario mostrato dalla fonte</p></div><a href={e.source_url} aria-label={`Fonte log ${e.team_key}`} target="_blank" rel="noreferrer"><ArrowUpRight size={18}/></a></div>)}<p className="footnote">Il log iniziale è stato verificato e trascritto. Autore e fuso non sono ancora risolti automaticamente.</p></div></section></div>
      </TabsContent>
      <TabsContent value="competition"><div className="page-heading"><div><div className="eyebrow">CheFantaVitaE10 · Classic</div><h1>Competizione Serie A</h1><div className="sync-note">Calendario e impostazioni verificati · 9 settembre 2026</div></div><Trophy size={35} className="muted"/></div><div className="competition-header"><div className="panel number-card"><strong>10</strong><span>Squadre partecipanti</span></div><div className="panel number-card"><strong>35</strong><span>Giornate di lega</span></div><div className="panel number-card"><strong>4—38</strong><span>Giornate di Serie A</span></div></div><div className="history-grid"><section className="panel"><div className="panel-head"><h2>Incontri · giornata 1</h2><span className="badge unknown">Non calcolati</span></div>{fixtures.map(([a,b])=><div className="fixture" key={a}><strong>{a}</strong><span>VS</span><strong>{b}</strong></div>)}<p className="footnote px-6 pb-4">Abbinamenti rilevati il 9 settembre. Risultati successivi non ancora acquisiti.</p></section><section className="panel"><div className="panel-head"><h2>Classifica e fantapunti</h2></div><Blank title="Risultati non ancora disponibili" description="Nell’archivio verificato non ci sono risultati calcolati. Classifica, andamento e rendimento saranno disponibili dopo l’integrazione dei punteggi."/></section></div></TabsContent>
    </Tabs>
    <footer className="bottom-bar"><span>FANTAMONITOR · CheFantaVitaE10</span><span>Archivio delle osservazioni · sincronizzazione automatica non attiva</span></footer>
    <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent><DialogHeader><DialogTitle>Importa una lettura</DialogTitle><DialogDescription>Archivia un file JSON prodotto dal connettore FANTAMONITOR.</DialogDescription></DialogHeader><div className="import-body"><div className="upload-box"><FileUp className="muted" size={28}/><label htmlFor="snapshot-file">File delle osservazioni</label><input id="snapshot-file" key={message} type="file" accept=".json,application/json" onChange={e=>{setFile(e.target.files?.[0]??null);setMessage('');setImportError('')}}/></div><p className="import-note">Massimo 256 KB. Puoi importare una singola lettura o un elenco. Le letture già presenti non vengono duplicate.</p>{importError&&<p role="alert" className="import-error">{importError}</p>}{message&&<p role="status" className="success-message">{message}</p>}<button className="btn primary" disabled={!file||importing} onClick={upload}>{importing?<RefreshCw className="spin"/>:<Database/>}{importing?'Archiviazione…':'Verifica e archivia'}</button></div></DialogContent></Dialog>
    <Sheet open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><SheetContent className="drawer"><SheetHeader className="p-0"><span className="eyebrow">Giornata {round}</span>{detail&&<Crest name={detail}/>}<SheetTitle>{detail}</SheetTitle><SheetDescription>Presenza osservata e tracce disponibili.</SheetDescription></SheetHeader><Status present={current?.teams.find(t=>t.name===detail)?.present}/><h3>OSSERVAZIONI</h3>{!detailRows.length?<p className="muted">Nessuna lettura per questa giornata.</p>:[...detailRows].reverse().map(s=><div className="timeline-row" key={s.observed_at}><div><strong>{displayDate(s.observed_at)}</strong><p>{s.teams.find(t=>t.name===detail)?.present?'Presente nel riepilogo admin':'Non inserita nel riepilogo admin'}</p></div></div>)}<h3>LOG DI INVIO</h3>{detailEvents.length?detailEvents.map((e,i)=><div className="event-box" key={i}><strong>{e.source_label}</strong><p>{e.source_time_text}</p><p>Data e ora come visualizzate sul sito.</p><a href={e.source_url} target="_blank" rel="noreferrer">Consulta la fonte ↗</a></div>):<p className="muted">Nessun log acquisito. Questo non dimostra l’assenza di un invio.</p>}<h3>GETTONI E PENALITÀ</h3><p className="muted">{detail?`${teamBalance(detail,halfForRound(Number(round)),data?.reviews??[]).remaining} gettone residuo nel girone · ${teamBalance(detail,halfForRound(Number(round)),data?.reviews??[]).penalty} € di penalità registrate.`:''}</p><button className="btn" onClick={()=>{setDetail(null);setView('penalties')}}>Consulta il registro verificato</button></SheetContent></Sheet>
  </div>
}
