import http from 'node:http';
import crypto from 'node:crypto';
import { chromium } from 'playwright';

const originalCreateServer=http.createServer.bind(http);
const secret=process.env.FANTAMONITOR_CONNECTOR_SECRET||'';
const username=process.env.FANTACALCIO_USERNAME||'';
const password=process.env.FANTACALCIO_PASSWORD||'';
const league='chefantavitae10',competition='337500';
const teamNames=['AC Idovalproico','Atletico Fontanelle','FC LBVLA','FC SEMINI','FC Villaggio Mau Mau','FDS Sballo','I PIPPISTRELLI','Pro Spritz','Real Hasbulla','Salamandre'];
const sign=(timestamp,body)=>crypto.createHmac('sha256',secret).update(`${timestamp}.${body}`).digest('hex');
function auth(req,raw){const ts=String(req.headers['x-fm-timestamp']||''),sig=String(req.headers['x-fm-signature']||'');const age=Math.abs(Date.now()-Number(ts));if(!secret||!/^\d+$/.test(ts)||age>=120000||sig.length!==64)return false;const expected=sign(ts,raw);return crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected));}
function signedJson(res,status,body,ts){const raw=JSON.stringify(body);res.writeHead(status,{'content-type':'application/json','cache-control':'no-store','x-fm-signature':sign(ts,raw)});res.end(raw);}
function score(result){if(typeof result!=='string')return null;const m=result.match(/(\d+)\s*[-:]\s*(\d+)/);return m?{home:Number(m[1]),away:Number(m[2])}:null;}
function standingRows(calendar,idToName){const rows=new Map(teamNames.map(name=>[name,{name,played:0,wins:0,draws:0,losses:0,goalsFor:0,goalsAgainst:0,points:0,fantasyTotal:0}]));for(const round of calendar){if(!round.calculated)continue;for(const match of round.matches||[]){const home=idToName.get(Number(match.tIdH)),away=idToName.get(Number(match.tIdA));if(!home||!away)continue;const h=rows.get(home),a=rows.get(away),s=score(match.result);h.played++;a.played++;h.points+=Number(match.standingPtH)||0;a.points+=Number(match.standingPtA)||0;h.fantasyTotal+=Number(match.ptH)||0;a.fantasyTotal+=Number(match.ptA)||0;if(s){h.goalsFor+=s.home;h.goalsAgainst+=s.away;a.goalsFor+=s.away;a.goalsAgainst+=s.home;if(s.home>s.away){h.wins++;a.losses++;}else if(s.home<s.away){a.wins++;h.losses++;}else{h.draws++;a.draws++;}}}}return [...rows.values()].sort((a,b)=>b.points-a.points||(b.goalsFor-b.goalsAgainst)-(a.goalsFor-a.goalsAgainst)||b.fantasyTotal-a.fantasyTotal);}
async function captureCompetition(){if(!username||!password)throw new Error('connector_credentials_missing');const browser=await chromium.launch({headless:true});const page=await browser.newPage();let calendar=null,teamsPayload=null;const listener=async r=>{if(r.status()!==200)return;const u=r.url();try{if(/\/onboarding\/v1\/league\/competition\/calendar\//.test(u))calendar=await r.json();if(/\/onboarding\/v1\/league\/competition\/teams/.test(u))teamsPayload=await r.json();}catch{}};page.on('response',listener);try{await page.goto('https://leghe.fantacalcio.it/login',{waitUntil:'domcontentloaded',timeout:20000});await page.locator('input[placeholder="Username"],input[autocomplete="username"]').first().fill(username);await page.locator('input[placeholder="Password"],input[autocomplete="current-password"]').first().fill(password);await page.getByRole('button',{name:'LOGIN'}).click();await Promise.race([page.waitForURL(u=>!/\/login(?:\/|$)/i.test(new URL(u).pathname),{timeout:15000}),page.waitForTimeout(3000)]);await page.goto(`https://leghe.fantacalcio.it/${league}/view/competition/${competition}/dashboard`,{waitUntil:'networkidle',timeout:30000});if(!Array.isArray(calendar)||!Array.isArray(teamsPayload?.data))throw new Error('competition_payload_missing');const idToName=new Map(teamsPayload.data.map(t=>[Number(t.id),String(t.n||'').trim()]));const normalized=calendar.map(r=>({round:Number(r.matchDay),championshipRound:Number(r.championshipMatchDay),calculated:Boolean(r.calculated),matches:(r.matches||[]).map(m=>{const s=score(m.result);return {homeId:Number(m.tIdH),awayId:Number(m.tIdA),home:idToName.get(Number(m.tIdH))||String(m.tIdH),away:idToName.get(Number(m.tIdA))||String(m.tIdA),homeFantasy:r.calculated?Number(m.ptH):null,awayFantasy:r.calculated?Number(m.ptA):null,homeStandingPoints:r.calculated?Number(m.standingPtH):null,awayStandingPoints:r.calculated?Number(m.standingPtA):null,homeGoals:s?.home??null,awayGoals:s?.away??null,result:r.calculated&&m.result&&m.result!=='-'?String(m.result):null,resultSR:r.calculated&&m.resultSR?String(m.resultSR):null};})}));const matches=normalized.flatMap(r=>r.calculated?r.matches.filter(m=>m.homeGoals!=null&&m.awayGoals!=null).map(m=>({round:r.round,home:m.home,away:m.away,homeGoals:m.homeGoals,awayGoals:m.awayGoals,homeFantasy:m.homeFantasy,awayFantasy:m.awayFantasy})):[]);return {source:`https://leghe.fantacalcio.it/${league}/view/competition/${competition}/dashboard`,fetchedAt:new Date().toISOString(),calendar:normalized,matches,standings:standingRows(calendar,idToName),warnings:calendar.some(r=>r.calculated)?[]:['Nessuna giornata della lega è ancora stata calcolata.']};}finally{page.off('response',listener);await browser.close();}}

http.createServer=function(listener,...args){return originalCreateServer(async(req,res)=>{const path=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`).pathname;if(path!=='/competition'||req.method!=='POST')return listener(req,res);let raw='';for await(const chunk of req)raw+=chunk;if(raw.length>4096){res.writeHead(413);return res.end();}const ts=String(req.headers['x-fm-timestamp']||'');if(!auth(req,raw)){res.writeHead(401,{'content-type':'application/json'});return res.end(JSON.stringify({error:'connector_signature_invalid'}));}try{const data=await captureCompetition();signedJson(res,200,{competition:data},ts);}catch(error){console.error('competition_capture_failed',error instanceof Error?error.message:error);signedJson(res,502,{error:'competition_capture_failed'},ts);}},...args);};
